spring:
  application:
    name: Spring-Boot-Transactions
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true